[workspace]
members = ["collector", "site", "database", "intern"]
exclude = ["collector/benchmarks", "rust/src"]

[profile.release.package.site]
debug = 1

[profile.release.package.collector]
debug = 1
